const sampleListings = [
    {
        title: "Cozy Beachfront Cottage",
        description: "A peaceful cottage right by the beach, perfect for a relaxing getaway.",
        image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
        price: 2500,
        location: "Goa",
        country: "India",
    },
    {
        title: "Modern Apartment in Mumbai",
        description: "A stylish apartment in the heart of Mumbai, close to restaurants and nightlife.",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
        price: 4500,
        location: "Mumbai",
        country: "India",
    },
    {
        title: "Mountain Cabin",
        description: "A beautiful wooden cabin surrounded by mountains and nature.",
        image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
        price: 3200,
        location: "Manali",
        country: "India",
    },
    {
        title: "Luxury Villa with Pool",
        description: "A spacious luxury villa featuring a private pool and stunning views.",
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=60",
        price: 8500,
        location: "Udaipur",
        country: "India",
    },
    {
        title: "Forest Retreat",
        description: "A cozy stay surrounded by dense forests, perfect for nature lovers.",
        image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
        price: 2800,
        location: "Coorg",
        country: "India",
    },
    {
        title: "Ocean View House",
        description: "Wake up to beautiful ocean views from this comfortable seaside home.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
        price: 6000,
        location: "Pondicherry",
        country: "India",
    },
    {
        title: "Snowy Mountain Lodge",
        description: "A warm and comfortable lodge surrounded by snowy mountains.",
        image: "https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=800&q=60",
        price: 5000,
        location: "Shimla",
        country: "India",
    },
    {
        title: "Desert Camp",
        description: "Experience the beauty of the desert with a unique and comfortable stay.",
        image: "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=800&q=60",
        price: 3500,
        location: "Jaisalmer",
        country: "India",
    },
    {
        title: "Hillside Cottage",
        description: "A peaceful cottage overlooking green valleys and beautiful hills.",
        image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
        price: 2900,
        location: "Mussoorie",
        country: "India",
    },
    {
        title: "Royal Palace Stay",
        description: "Experience traditional Indian luxury in a beautiful royal-style property.",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=60",
        price: 7500,
        location: "Jaipur",
        country: "India",
    },
    {
        title: "Lakeside Retreat",
        description: "A relaxing home beside a peaceful lake surrounded by nature.",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
        price: 4200,
        location: "Nainital",
        country: "India",
    },
    {
        title: "Beach House",
        description: "A beautiful beach house with direct access to the sandy shore.",
        image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=60",
        price: 5500,
        location: "Alibaug",
        country: "India",
    },
    {
        title: "Luxury City Loft",
        description: "A modern loft located close to the best attractions in the city.",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
        price: 4800,
        location: "Bangalore",
        country: "India",
    },
    {
        title: "Tea Estate Cottage",
        description: "Stay among beautiful tea gardens in a peaceful mountain setting.",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
        price: 3400,
        location: "Munnar",
        country: "India",
    },
    {
        title: "Riverside Villa",
        description: "A spacious villa overlooking a beautiful river and green landscape.",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
        price: 6200,
        location: "Rishikesh",
        country: "India",
    },
    {
        title: "Heritage Haveli",
        description: "A charming heritage property offering traditional architecture and comfort.",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
        price: 3900,
        location: "Jodhpur",
        country: "India",
    },
    {
        title: "Tropical Villa",
        description: "A tropical villa surrounded by palm trees and beautiful gardens.",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
        price: 7000,
        location: "Goa",
        country: "India",
    },
    {
        title: "Countryside Farmhouse",
        description: "A quiet farmhouse perfect for escaping the noise of the city.",
        image: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=800&q=60",
        price: 3100,
        location: "Lonavala",
        country: "India",
    },
    {
        title: "Modern Studio",
        description: "A compact modern studio with everything needed for a comfortable stay.",
        image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=60",
        price: 2200,
        location: "Delhi",
        country: "India",
    },
    {
        title: "Valley View Home",
        description: "A comfortable home offering spectacular views of the surrounding valley.",
        image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
        price: 3600,
        location: "Kasauli",
        country: "India",
    },
    {
        title: "Luxury Penthouse",
        description: "A premium penthouse with panoramic city views and elegant interiors.",
        image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=800&q=60",
        price: 9500,
        location: "Mumbai",
        country: "India",
    },
    {
        title: "Secluded Beach Villa",
        description: "A private villa for guests looking for peace, privacy, and ocean views.",
        image: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=800&q=60",
        price: 7800,
        location: "Andaman",
        country: "India",
    },
    {
        title: "Mountain View Apartment",
        description: "A modern apartment with breathtaking views of the Himalayan mountains.",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
        price: 3800,
        location: "Manali",
        country: "India",
    },
    {
        title: "Lakefront Cabin",
        description: "A cozy wooden cabin sitting right beside a peaceful mountain lake.",
        image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
        price: 4100,
        location: "Nainital",
        country: "India",
    },
    {
        title: "Rooftop Apartment",
        description: "A stylish apartment with a private rooftop and beautiful city views.",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=60",
        price: 4300,
        location: "Delhi",
        country: "India",
    },
    {
        title: "Jungle Retreat",
        description: "A peaceful jungle stay surrounded by wildlife and lush greenery.",
        image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
        price: 3300,
        location: "Wayanad",
        country: "India",
    },
    {
        title: "Sunset Beach Resort",
        description: "Enjoy stunning sunsets from this comfortable property near the beach.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
        price: 5900,
        location: "Goa",
        country: "India",
    },
    {
        title: "Colonial House",
        description: "A beautiful colonial-era home combining history with modern comfort.",
        image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=60",
        price: 3500,
        location: "Kolkata",
        country: "India",
    },
    {
        title: "Hilltop Villa",
        description: "A luxurious villa sitting on a hilltop with panoramic valley views.",
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=60",
        price: 8200,
        location: "Dehradun",
        country: "India",
    },
    {
        title: "Coastal Apartment",
        description: "A bright apartment located just minutes away from the coast.",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
        price: 3700,
        location: "Kochi",
        country: "India",
    },
    {
        title: "Luxury Desert Villa",
        description: "A luxurious desert property offering an unforgettable experience.",
        image: "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=800&q=60",
        price: 6800,
        location: "Jaisalmer",
        country: "India",
    },
    {
        title: "Garden Cottage",
        description: "A charming cottage surrounded by flowers and peaceful gardens.",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
        price: 2700,
        location: "Pune",
        country: "India",
    },
    {
        title: "Himalayan Retreat",
        description: "A peaceful retreat surrounded by pine forests and Himalayan peaks.",
        image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
        price: 4500,
        location: "Kasol",
        country: "India",
    },
    {
        title: "Modern Villa",
        description: "A contemporary villa with spacious rooms and a private garden.",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
        price: 7200,
        location: "Hyderabad",
        country: "India",
    },
    {
        title: "Oceanfront Villa",
        description: "A luxurious oceanfront villa with direct access to the beach.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
        price: 9000,
        location: "Kerala",
        country: "India",
    },
    {
        title: "Peaceful Homestay",
        description: "A welcoming homestay offering a quiet and comfortable experience.",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=60",
        price: 1800,
        location: "Rishikesh",
        country: "India",
    },
    {
        title: "Snow Valley Cabin",
        description: "A warm cabin surrounded by snow-covered mountains and forests.",
        image: "https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=800&q=60",
        price: 4700,
        location: "Gulmarg",
        country: "India",
    },
    {
        title: "Heritage Palace",
        description: "Stay in an elegant heritage property filled with history and charm.",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
        price: 8800,
        location: "Udaipur",
        country: "India",
    },
    {
        title: "Forest Cabin",
        description: "A secluded cabin deep inside a peaceful forest.",
        image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
        price: 3000,
        location: "Jim Corbett",
        country: "India",
    },
    {
        title: "City Center Flat",
        description: "A convenient apartment located close to shopping and major attractions.",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
        price: 2900,
        location: "Bangalore",
        country: "India",
    },
    {
        title: "Palm Tree Villa",
        description: "A tropical villa surrounded by palm trees and beautiful greenery.",
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=60",
        price: 6500,
        location: "Goa",
        country: "India",
    },
    {
        title: "Riverside Cottage",
        description: "A cozy cottage with peaceful river views and fresh mountain air.",
        image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=60",
        price: 3100,
        location: "Rishikesh",
        country: "India",
    },
    {
        title: "Tea Garden Retreat",
        description: "A relaxing property surrounded by endless green tea plantations.",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
        price: 3600,
        location: "Darjeeling",
        country: "India",
    },
    {
        title: "Royal Haveli",
        description: "A beautifully restored haveli offering a traditional royal experience.",
        image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=800&q=60",
        price: 5400,
        location: "Jodhpur",
        country: "India",
    },
    {
        title: "Beachside Apartment",
        description: "A comfortable apartment with easy access to the beach and local cafes.",
        image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
        price: 4200,
        location: "Pondicherry",
        country: "India",
    },
    {
        title: "Mountain Escape",
        description: "A peaceful mountain home perfect for relaxing and disconnecting.",
        image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
        price: 3400,
        location: "Manali",
        country: "India",
    },
    {
        title: "Luxury Pool House",
        description: "A premium house featuring a private pool and spacious outdoor area.",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
        price: 8000,
        location: "Lonavala",
        country: "India",
    },
    {
        title: "Seaside Cottage",
        description: "A cozy cottage where you can enjoy peaceful mornings beside the sea.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
        price: 3900,
        location: "Alibaug",
        country: "India",
    },
    {
        title: "Valley Cottage",
        description: "A small cottage with beautiful views of green valleys and hills.",
        image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
        price: 2600,
        location: "Mussoorie",
        country: "India",
    },
    {
        title: "Luxury City Apartment",
        description: "A stylish apartment with modern furniture and excellent city access.",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=60",
        price: 5200,
        location: "Delhi",
        country: "India",
    },
    {
        title: "Jungle Lodge",
        description: "A comfortable lodge surrounded by forests and natural beauty.",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
        price: 4300,
        location: "Wayanad",
        country: "India",
    },
    {
        title: "Lakeside Villa",
        description: "A beautiful villa overlooking a calm lake and surrounding mountains.",
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=60",
        price: 7600,
        location: "Udaipur",
        country: "India",
    },
    {
        title: "Cozy Studio Apartment",
        description: "A clean and modern studio perfect for solo travelers and couples.",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
        price: 2100,
        location: "Pune",
        country: "India",
    },
    {
        title: "Desert Heritage Home",
        description: "A traditional home offering an authentic desert experience.",
        image: "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=800&q=60",
        price: 3300,
        location: "Jaisalmer",
        country: "India",
    },
    {
        title: "Hillside Homestay",
        description: "A friendly homestay with beautiful views and peaceful surroundings.",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
        price: 2300,
        location: "Shimla",
        country: "India",
    },
    {
        title: "Private Beach Villa",
        description: "A spacious private villa just steps away from the ocean.",
        image: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=800&q=60",
        price: 8400,
        location: "Goa",
        country: "India",
    },
    {
        title: "Modern Hillside Home",
        description: "A contemporary home surrounded by mountains and fresh air.",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
        price: 4600,
        location: "Kasauli",
        country: "India",
    },
    {
        title: "Riverside Retreat",
        description: "A peaceful riverside property perfect for a relaxing weekend.",
        image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=60",
        price: 3500,
        location: "Rishikesh",
        country: "India",
    },
    {
        title: "Colonial Villa",
        description: "A historic villa featuring classic architecture and modern amenities.",
        image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=60",
        price: 5700,
        location: "Kolkata",
        country: "India",
    },
    {
        title: "Luxury Lake House",
        description: "A luxurious lake house with large windows and beautiful views.",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
        price: 7900,
        location: "Nainital",
        country: "India",
    },
    {
        title: "Forest View Apartment",
        description: "A modern apartment overlooking lush green forests.",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=60",
        price: 3200,
        location: "Coorg",
        country: "India",
    },
    {
        title: "Snow Mountain Villa",
        description: "A warm luxury villa with spectacular snow-covered mountain views.",
        image: "https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=800&q=60",
        price: 6800,
        location: "Gulmarg",
        country: "India",
    },
    {
        title: "Tropical Beach Cottage",
        description: "A colorful cottage surrounded by tropical greenery near the beach.",
        image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
        price: 3100,
        location: "Goa",
        country: "India",
    },
    {
        title: "City View Penthouse",
        description: "A premium penthouse with stunning views across the city skyline.",
        image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=800&q=60",
        price: 9800,
        location: "Mumbai",
        country: "India",
    },
    {
        title: "Peaceful Mountain Cabin",
        description: "A secluded cabin surrounded by pine trees and mountain scenery.",
        image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
        price: 3700,
        location: "Kasol",
        country: "India",
    },
    {
        title: "Garden Villa",
        description: "A spacious villa surrounded by beautiful gardens and greenery.",
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=60",
        price: 6100,
        location: "Pune",
        country: "India",
    },
    {
        title: "Ocean Breeze Home",
        description: "A bright seaside home where you can relax and enjoy the ocean breeze.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
        price: 4800,
        location: "Kochi",
        country: "India",
    },
    {
        title: "Royal City Residence",
        description: "An elegant residence inspired by traditional Indian royal architecture.",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
        price: 7300,
        location: "Jaipur",
        country: "India",
    },
    {
        title: "Countryside Cottage",
        description: "A charming cottage surrounded by fields and peaceful countryside.",
        image: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=800&q=60",
        price: 2400,
        location: "Lonavala",
        country: "India",
    },
    {
        title: "Modern Coastal Villa",
        description: "A modern villa with beautiful interiors and easy beach access.",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
        price: 6900,
        location: "Pondicherry",
        country: "India",
    },
    {
        title: "Himalayan Homestay",
        description: "A cozy homestay offering peaceful mountain views and fresh air.",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
        price: 2800,
        location: "Manali",
        country: "India",
    },
    {
        title: "Luxury Forest Villa",
        description: "A private luxury villa hidden among lush green forests.",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
        price: 7500,
        location: "Wayanad",
        country: "India",
    },
    {
        title: "Sunset Cottage",
        description: "A peaceful cottage offering beautiful sunset views every evening.",
        image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=60",
        price: 3000,
        location: "Goa",
        country: "India",
    },
    {
        title: "Mountain Luxury Lodge",
        description: "A premium lodge with cozy interiors and breathtaking mountain views.",
        image: "https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=800&q=60",
        price: 6400,
        location: "Shimla",
        country: "India",
    },
    {
        title: "Lake View Cottage",
        description: "A cozy cottage overlooking a peaceful lake surrounded by hills.",
        image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
        price: 2900,
        location: "Nainital",
        country: "India",
    },
    {
        title: "Beachfront Luxury Home",
        description: "A luxurious home with direct beach access and ocean views.",
        image: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=800&q=60",
        price: 8700,
        location: "Andaman",
        country: "India",
    },
    {
        title: "Traditional Haveli Stay",
        description: "Experience traditional architecture with comfortable modern rooms.",
        image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=800&q=60",
        price: 4400,
        location: "Jodhpur",
        country: "India",
    },
    {
        title: "Green Valley House",
        description: "A comfortable house overlooking a beautiful green valley.",
        image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
        price: 3500,
        location: "Mussoorie",
        country: "India",
    },
    {
        title: "Urban Luxury Flat",
        description: "A premium modern flat located in the heart of the city.",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=60",
        price: 5100,
        location: "Bangalore",
        country: "India",
    },
    {
        title: "Desert Sunset Camp",
        description: "Enjoy unforgettable sunsets and peaceful nights in the desert.",
        image: "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=800&q=60",
        price: 3600,
        location: "Jaisalmer",
        country: "India",
    },
    {
        title: "Riverside Luxury Villa",
        description: "A spacious luxury villa overlooking a peaceful river.",
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=60",
        price: 7100,
        location: "Rishikesh",
        country: "India",
    },
    {
        title: "Cozy City Home",
        description: "A comfortable home in a quiet neighborhood close to the city center.",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
        price: 2600,
        location: "Delhi",
        country: "India",
    },
    {
        title: "Tea Estate Villa",
        description: "A beautiful villa surrounded by peaceful tea plantations.",
        image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
        price: 5800,
        location: "Munnar",
        country: "India",
    },
    {
        title: "Palm Garden House",
        description: "A relaxing house surrounded by palm trees and tropical gardens.",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
        price: 4200,
        location: "Kerala",
        country: "India",
    },
    {
        title: "Hill Station Retreat",
        description: "A peaceful retreat with cool weather and beautiful mountain scenery.",
        image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
        price: 3100,
        location: "Ooty",
        country: "India",
    },
    {
        title: "Luxury Heritage Villa",
        description: "A grand heritage villa combining traditional design with modern luxury.",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
        price: 9200,
        location: "Udaipur",
        country: "India",
    },
];

module.exports = { data: sampleListings };